---
- hosts: all
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Install common packages
      apt:
        name:
          - wget
          - curl
          - python3-pip
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: present
        update_cache: yes

    - name: Install Filebeat
      apt:
        name: filebeat
        state: present
        update_cache: yes

    - name: Configure Filebeat
      copy:
        content: |
          filebeat.inputs:
          - type: file
            enabled: true
            paths:
              - /var/log/nginx/*.log
              - /var/log/apache2/*.log
              - /var/log/mysql/*.log

          output.elasticsearch:
            hosts: ["{{ remote_pc }}:9200"]

          processors:
            - add_host_metadata:
                when.not.contains.tags: forwarded
        dest: /etc/filebeat/filebeat.yml
      notify: Restart Filebeat

    - name: Install Node Exporter
      unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /usr/local/bin
        remote_src: yes

    - name: Create Node Exporter service file
      copy:
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=nobody
          Group=nobody
          Type=simple
          ExecStart=/usr/local/bin/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/node_exporter.service

    - name: Enable and start Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Allow necessary ports (iptables)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      loop: "{{ firewall_ports }}"

  handlers:
    - name: Restart Filebeat
      service:
        name: filebeat
        state: restarted

- hosts: remote_pc
  become: true
  tasks:
    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present
        update_cache: yes

    - name: Configure Elasticsearch
      copy:
        content: |
          network.host: 0.0.0.0
          http.port: 9200
          discovery.type: single-node
        dest: /etc/elasticsearch/elasticsearch.yml

    - name: Install Kibana
      apt:
        name: kibana
        state: present
        update_cache: yes

    - name: Configure Kibana
      copy:
        content: |
          server.port: 5601
          server.host: "0.0.0.0"
          elasticsearch.hosts: ["http://localhost:9200"]
        dest: /etc/kibana/kibana.yml

    - name: Start Elasticsearch service
      service:
        name: elasticsearch
        state: started
        enabled: true

    - name: Start Kibana service
      service:
        name: kibana
        state: started
        enabled: true

- hosts: nginx_load_balancer
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure Nginx as Load Balancer
      copy:
        content: |
          events {
              worker_connections 1024;
          }

          http {
              upstream backend {
                  server {{ apache_server_1 }}:80;
                  server {{ apache_server_2 }}:80;
              }

              server {
                  listen 80;

                  location / {
                      proxy_pass http://backend;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                  }
              }
          }
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

- hosts: apache_servers
  become: true
  tasks:
    - name: Install Apache and PHP packages
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - libapache2-mod-php
          - php-cli
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
        state: present
        update_cache: yes

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Download latest WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set permissions for WordPress
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        state: directory
        recurse: yes

    - name: Configure Apache for WordPress
      copy:
        content: |
          <VirtualHost *:80>
              ServerAdmin webmaster@localhost
              DocumentRoot /var/www/html/wordpress
              ServerName {{ wordpress_url }}

              <Directory /var/www/html/wordpress/>
                  Options FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>
        dest: /etc/apache2/sites-available/wordpress.conf

    - name: Enable WordPress site
      apache2_module:
        state: present
        name: wordpress.conf

    - name: Disable default Apache site
      apache2_module:
        state: absent
        name: 000-default.conf

    - name: Enable Apache rewrite module
      apache2_module:
        state: present
        name: rewrite

    - name: Configure wp-config.php
      copy:
        content: |
          <?php
          define('DB_NAME', '{{ mysql_db }}');
          define('DB_USER', '{{ wordpress_user }}');
          define('DB_PASSWORD', '{{ wordpress_password }}');
          define('DB_HOST', '{{ mysql_master }}');
          define('DB_CHARSET', 'utf8');
          define('DB_COLLATE', '');

          define('AUTH_KEY',         '{{ lookup('password', '/dev/null chars=ascii_letters length=64') }}');
          define('SECURE_AUTH_KEY',  '{{ lookup('password', '/dev/null chars=ascii_letters length=64') }}');
          define('LOGGED_IN_KEY',    '{{ lookup('password', '/dev/null chars=ascii_letters length=64') }}');
          define('NONCE_KEY',        '{{ lookup('password', '/dev/null chars=ascii_letters length=64') }}');
          define('AUTH_SALT',        '{{ lookup('password', '/dev/null chars=ascii_letters length=64') }}');
          define('SECURE_AUTH_SALT', '{{ lookup('password', '/dev/null chars=ascii_letters length=64') }}');
          define('LOGGED_IN_SALT',   '{{ lookup('password', '/dev/null chars=ascii_letters length=64') }}');
          define('NONCE_SALT',       '{{ lookup('password', '/dev/null chars=ascii_letters length=64') }}');

          $table_prefix = 'wp_';

          define('WP_DEBUG', false);

          if ( !defined('ABSPATH') )
              define('ABSPATH', dirname(__FILE__) . '/');

          require_once(ABSPATH . 'wp-settings.php');
        dest: /var/www/html/wordpress/wp-config.php

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted


- hosts: mysql_slave
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Stop MySQL Service on Slave
      service:
        name: mysql
        state: stopped

    - name: Backup MySQL Database on Slave
      command: "{{ mysql_backup_script }}"
      register: backup_result
      failed_when: backup_result.rc != 0
      changed_when: backup_result.rc == 0

    - name: Copy backup to master server
      copy:
        src: "{{ backup_result.stdout.split()[-1] }}"  # Assuming last line of output is backup file path
        dest: /tmp/mysql_backup.tar.gz
      delegate_to: "{{ mysql_master }}"

- hosts: mysql_master
  become: true
  tasks:
    - name: Stop MySQL Service on Master
      service:
        name: mysql
        state: stopped

    - name: Remove existing data directory
      file:
        path: /var/lib/mysql
        state: absent

    - name: Create new data directory
      file:
        path: /var/lib/mysql
        state: directory
        mode: 0700
        owner: mysql
        group: mysql

    - name: Extract the backup
      unarchive:
        src: /tmp/mysql_backup.tar.gz
        dest: /var/lib/mysql
        remote_src: yes

    - name: Restore database permissions
      command: chown -R mysql:mysql /var/lib/mysql

    - name: Start MySQL Service on Master
      service:
        name: mysql
        state: started

    - name: Remove backup file from master
      file:
        path: /tmp/mysql_backup.tar.gz
        state: absent

- hosts: mysql_slave
  become: true
  tasks:
    - name: Start MySQL Service on Slave
      service:
        name: mysql
        state: started

    - name: Reset Slave Replication
      mysql_replication:
        mode: reset_slave

    - name: Get master status
      mysql_replication:
        mode: getmaster
        login_host: "{{ mysql_master }}"
        login_user: "{{ mysql_replication_user }}"
        login_password: "{{ mysql_replication_password }}"
      register: master_status
      delegate_to: "{{ mysql_master }}"

    - name: Configure slave replication
      mysql_replication:
        mode: changemaster
        master_host: "{{ mysql_master }}"
        master_user: "{{ mysql_replication_user }}"
        master_password: "{{ mysql_replication_password }}"
        master_log_file: "{{ master_status.File }}"
        master_log_pos: "{{ master_status.Position }}"

    - name: Start slave
      mysql_replication:
        mode: startslave

- hosts: mysql_master
  become: true
  tasks:
    - name: Install MySQL Server
      apt:
        name:
          - mysql-server
          - python3-mysqldb
        state: present
        update_cache: yes

    - name: Configure MySQL for Replication (Master)
      blockinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        create: yes
        block: |
          [mysqld]
          server-id = 1
          log_bin = mysql-bin
          binlog_format = row
          gtid-mode=ON
          enforce-gtid-consistency
          log-replica-updates
          bind-address = 0.0.0.0
      notify: Restart MySQL

    - name: Set MySQL Root Password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: localhost
        state: present

    - name: Create WordPress database
      mysql_db:
        name: "{{ mysql_db }}"
        state: present

    - name: Create Replication User
      mysql_user:
        name: "{{ mysql_replication_user }}"
        password: "{{ mysql_replication_password }}"
        host: '%'
        priv: '*.*:REPLICATION SLAVE,REPLICATION CLIENT'
        state: present

    - name: Create WordPress User
      mysql_user:
        name: "{{ wordpress_user }}"
        password: "{{ wordpress_password }}"
        priv: '{{ mysql_db }}.*:ALL'
        state: present

    - name: Download MySQLD Exporter
      get_url:
        url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqld_exporter_version }}/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/mysqld_exporter.tar.gz

    - name: Extract MySQLD Exporter
      unarchive:
        src: /tmp/mysqld_exporter.tar.gz
        dest: /usr/local/bin
        remote_src: yes

    - name: Create MySQLD Exporter service file
      copy:
        content: |
          [Unit]
          Description=MySQLD Exporter
          After=network.target mysqld.service

          [Service]
          User=nobody
          Group=nobody
          Type=simple
          ExecStart=/usr/local/bin/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64/mysqld_exporter

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/mysqld_exporter.service

    - name: Enable and start MySQLD Exporter service
      systemd:
        name: mysqld_exporter
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted

- hosts: mysql_slave
  become: true
  tasks:
    - name: Install MySQL Server
      apt:
        name:
          - mysql-server
          - python3-mysqldb
        state: present
        update_cache: yes

    - name: Configure MySQL for Replication (Slave)
      blockinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        create: yes
        block: |
          [mysqld]
          server-id = 2
          relay-log = /var/log/mysql/mysql-relay-bin.log
          log_bin = /var/log/mysql/mysql-bin.log
          binlog_do_db = {{ mysql_db }}
          bind-address = 0.0.0.0
      notify: Restart MySQL

    - name: Set MySQL Root Password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: localhost
        state: present

    - name: Download MySQLD Exporter
      get_url:
        url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqld_exporter_version }}/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/mysqld_exporter.tar.gz

    - name: Extract MySQLD Exporter
      unarchive:
        src: /tmp/mysqld_exporter.tar.gz
        dest: /usr/local/bin
        remote_src: yes

    - name: Create MySQLD Exporter service file
      copy:
        content: |
          [Unit]
          Description=MySQLD Exporter
          After=network.target mysqld.service

          [Service]
          User=nobody
          Group=nobody
          Type=simple
          ExecStart=/usr/local/bin/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64/mysqld_exporter

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/mysqld_exporter.service

    - name: Enable and start MySQLD Exporter service
      systemd:
        name: mysqld_exporter
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
